version: "3"
services:
  lab:
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
    #image: jupyterlab
    #container_name: jupyterlab
    networks:
      - jupyterlab-network
    ports:
      - "8000:8888"

networks:
  jupyterlab-network:
    name: jupyterlab-network

                                              
